name: Build

on: [push]

jobs: 
  build:
    name: build
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: VcPkg
      uses: lukka/run-vcpkg@v11
      with:
        setupOnly: true
        vcpkgGitCommitId: 5b1214315250939257ef5d62ecdcbca18cf4fb1c
    - name: Install Prerequiements
      run: |
           echo Installing packages...
           sudo apt-get install -y build-essential autoconf autoconf-archive libtool
    - name: Build
      run: |
           cmake . -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake
           cmake --build build --config Debug --target all 
    - name: Archive logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs-qt
        path: /home/runner/work/HexSmw/HexSmw/vcpkg/buildtrees/qtbase/*.log




