name: Linux

on: [push]

jobs: 
  build:
    name: build
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: VcPkg
      uses: lukka/run-vcpkg@v11
      with:
        setupOnly: true
        vcpkgGitCommitId: 5b1214315250939257ef5d62ecdcbca18cf4fb1c
    - name: Install Prerequiements
      run: |
           echo Installing packages...
           sudo apt-get update -y
           sudo apt-get install -y build-essential autoconf autoconf-archive libtool
           sudo apt-get install -y libgl1-mesa-dev libxcb-xinerama0-dev libudev-dev libxkbcommon-dev libwayland-dev libegl1-mesa-dev libgles2-mesa-dev libglu1-mesa-dev
    - name: Build
      run: |
           mkdir build && cd build
           cmake .. -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake
           cmake --build . --config Debug --target all 
    - name: Archive logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs-qt
        path: /home/runner/work/HexSmw/HexSmw/build/*




