name: Linux

on: [push]

jobs: 
  build:
    name: linux
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: VcPkg
      uses: lukka/run-vcpkg@v11
      with:
        setupOnly: true
        vcpkgGitCommitId: 5b1214315250939257ef5d62ecdcbca18cf4fb1c
    - name: Install Prerequiements
      run: |
           echo Installing packages...
           sudo apt-get update -y
           sudo apt-get install -y build-essential autoconf autoconf-archive libtool 
           sudo apt-get install -y libgl1-mesa-dev libxcb-xinerama0-dev libudev-dev libxkbcommon-dev libwayland-dev libegl1-mesa-dev libgles2-mesa-dev libglu1-mesa-dev
           sudo apt-get install -y dh-make debhelper devscripts fakeroot
    - name: Build
      run: |
           mkdir build && cd build
           cmake .. -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake -DCMAKE_VERBOSE_MAKEFILE=ON
           cmake --build . --config Debug --target all 
           ldd /home/runner/work/HexSmw/HexSmw/build/HexSmw
           file /home/runner/work/HexSmw/HexSmw/build/HexSmw
    - name: Build deb file
      run: |
           cd /tmp
           mkdir -p smw/DEBIAN
           mkdir -p smw/usr/bin
           echo "Package: hexsmw" > smw/DEBIAN/control
           echo "Section: base" >> smw/DEBIAN/control
           echo "Version: 0.0.1" >> smw/DEBIAN/control
           echo "Priority: optional" >> smw/DEBIAN/control
           echo "Architecture: amd64" >> smw/DEBIAN/control
           echo "Depends: libqt6gui6 " >> smw/DEBIAN/control
           echo "Maintainer: Markus Wegehaupt <>" >> smw/DEBIAN/control
           echo "Homepage: https://" >> smw/DEBIAN/control
           echo "Description: HexSmw" >> smw/DEBIAN/control
           echo " Hex editor" >> smw/DEBIAN/control
           cp /home/runner/work/HexSmw/HexSmw/build/HexSmw smw/usr/bin
           dpkg-deb --build smw
    - name: Linux Binary Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: hexsmw-linux-binary
        path: /tmp/smw.deb
        #/home/runner/work/HexSmw/HexSmw/build/HexSmw










        
        